(()=>{'use strict';const M=DeskModel,$=s=>document.querySelector(s);let state,tab='projects',sort='priority',blocked=false,feedback='',saveKey='saved',lastDate=M.today(),chatBusy=false,chatID=null;const t=()=>DeskStrings[state?.language||'en'];const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};const button=(text,fn)=>{const n=node('button',text);n.type='button';n.onclick=fn;return n};const label=(text,input)=>{const n=node('label',text);n.append(input);return n};const select=(pairs,value)=>{const n=node('select');pairs.forEach(([v,text])=>{const o=node('option',text);o.value=v;n.append(o)});n.value=value;return n};
function save(){if(blocked)return;saveKey='saving';$('#save-status').textContent=t()[saveKey];if(window.webkit?.messageHandlers?.desk)window.webkit.messageHandlers.desk.postMessage(state);else saved(false)}window.saved=ok=>{saveKey=ok?'saved':'saveError';$('#save-status').textContent=t()[saveKey]};
function dueLabel(x){if(!x.due)return t().noDue;const d=M.days(x.due);return d===0?t().today:Math.abs(d)+' '+(d<0?t().late:t().left)}
function commit(){save();render()}
function closeEditor(){$('#editor').hidden=true;$('#editor').replaceChildren()}
function render(){if(!state)return;const s=t();document.documentElement.lang=state.language;$('#language').value=state.language;const nav=$('nav');nav.replaceChildren();['projects','notes'].forEach(k=>{const b=button(s[k],()=>{tab=k;closeEditor();render()});b.setAttribute('aria-pressed',String(tab===k));nav.append(b)});$('#heading').textContent=s[tab];const totals=M.totals(state.projects);$('#metrics').textContent=tab==='projects'?`${s.count} ${state.projects.length} · ${s.total} ${totals.total} · ${s.average} ${totals.average.toFixed(2)}`:'';$('#sort').hidden=tab==='projects';$('#sort').replaceChildren(...[['priority',s.byPriority],['due',s.byDate]].map(([v,x])=>{const n=node('option',x);n.value=v;return n}));$('#sort').value=sort;$('#add').textContent=tab==='projects'?s.addProject:s.addTodo;$('#legend').textContent=tab==='projects'?s.legend:s.emptyTodos.split('.')[1]||s.local;
const target=M.target(state),level=M.level(target);$('#pet').dataset.level=level;$('#pet').setAttribute('aria-label',[s.quiet,s.focus,s.urgent][level]);$('#reason').textContent=target?`${[s.quiet,s.focus,s.urgent][level]} · ${s.priority} ${target.item.priority} · ${s.unrecorded}: ${Math.max(0,M.ordinal(M.today())-M.ordinal(target.item.last))} · ${s.postponed}: ${target.item.delays}`:'';$('#nag').textContent=feedback||(target?target.item.name+' — '+s.lines[level][M.ordinal(M.today())%3]:s.allDone);$('#reminder-actions').replaceChildren();if(target){$('#reminder-actions').append(button(s.view,()=>{tab=target.kind;closeEditor();render()}),button(s.delay,()=>{target.item.delays++;feedback='';commit()}))}
const content=$('#content');content.replaceChildren();if(tab==='projects'){if(!state.projects.length)content.append(node('p',s.emptyProjects));else{const wrap=node('div',undefined,'table-wrap'),table=node('table'),head=node('thead'),tr=node('tr');[s.name,...M.stages[state.language],s.remaining].forEach(x=>tr.append(node('th',x)));head.append(tr);table.append(head);const body=node('tbody');state.projects.slice().sort((a,b)=>a.priority-b.priority).forEach(p=>{const row=node('tr');const name=node('td');name.append(button(p.name,()=>editProject(p)));if(M.score(p)===0&&p.steps.some((_,i)=>M.applicable(p,i)))name.className='finished';const linked=state.todos.filter(x=>x.project===p.id&&!x.done&&x.due).sort((a,b)=>M.days(a.due)-M.days(b.due))[0];name.append(node('small',`${s.priority} ${p.priority}`+(linked?' · '+dueLabel(linked):'')));row.append(name);p.steps.forEach((done,i)=>{const td=node('td');const b=button('',()=>{p.steps[i]=!p.steps[i];feedback=p.steps[i]?s.ack:'';if(p.steps[i]){p.last=M.today();p.delays=0}commit()});b.className='stage'+(target?.kind==='projects'&&target.item.id===p.id&&i===M.nextStage(p)?' focus':'');b.disabled=!M.applicable(p,i);if(b.disabled){b.classList.add('excluded');b.textContent='—'}b.setAttribute('aria-pressed',String(done));b.setAttribute('aria-label',p.name+' · '+M.stageName(p,i,state.language)+(b.disabled?' · '+s.notApplicable:''));b.title=b.getAttribute('aria-label');if((p.stageNames||[])[i])td.append(node('small',M.stageName(p,i,state.language),'custom-stage'));td.append(b);row.append(td)});row.append(node('td',String(M.score(p))));body.append(row)});table.append(body);wrap.append(table);content.append(wrap)}}else{if(!state.todos.length)content.append(node('p',s.emptyTodos));state.todos.slice().sort((a,b)=>Number(a.done)-Number(b.done)||(sort==='due'?M.days(a.due)-M.days(b.due)||a.priority-b.priority:a.priority-b.priority||M.days(a.due)-M.days(b.due))).forEach(x=>{const row=node('div',undefined,'todo'),check=node('input');check.type='checkbox';check.checked=x.done;check.id='todo-'+x.id;check.onchange=()=>{x.done=check.checked;x.last=M.today();x.delays=0;feedback=x.done?s.ack:'';commit()};const text=node('label',x.name,x.done?'finished':'');text.htmlFor=check.id;const p=state.projects.find(p=>p.id===x.project);text.append(node('small',s.priority+' '+x.priority+(p?' · '+p.name:'')));row.append(check,text,node('span',x.done?s.done:dueLabel(x),'due'+(!x.done&&M.days(x.due)<=2?' urgent':'')));content.append(row)})}$('#chat-title').textContent=s.chat;$('#chat-disclaimer').textContent=s.chatPrivacy;$('#question').placeholder=s.placeholder;$('#question').setAttribute('aria-label',s.chat);$('#send').textContent=s.send;$('#privacy').textContent=s.local;$('#save-status').textContent=s[saveKey];$('#mini-toggle').textContent=s.mini;$('#chat-reset').textContent=s.newChat;$('#chat-cancel').textContent=s.cancel;$('#chat-cancel').hidden=!chatBusy;$('#send').disabled=chatBusy;renderChat()}
function editor(){const s=t(),f=$('#editor');f.replaceChildren();f.hidden=false;const name=node('input');name.required=true;name.maxLength=100;f.append(label(tab==='projects'?s.projectName:s.taskName,name));const priority=select([['1',s.critical],['2',s.important],['3',s.normal]],'2');f.append(label(s.priority,priority));let checks=[],due,project;if(tab==='projects'){f.append(node('small',s.completed));const group=node('div',undefined,'checks');M.stages[state.language].forEach(x=>{const n=node('input');n.type='checkbox';checks.push(n);group.append(label(x,n))});f.append(group)}else{due=node('input');due.type='date';project=select([['',s.none],...state.projects.map(p=>[p.id,p.name])],'');f.append(label(s.due,due),label(s.link,project))}const actions=node('div',undefined,'buttons');const submit=node('button',s.add);submit.type='submit';actions.append(button(s.cancel,closeEditor),submit);f.append(actions);const kind=tab;f.onsubmit=e=>{e.preventDefault();if(!name.value.trim())return;const item={id:crypto.randomUUID(),name:name.value.trim(),priority:Number(priority.value),last:M.today(),delays:0};if(kind==='projects')state.projects.push({...item,steps:checks.map(n=>n.checked)});else state.todos.push({...item,due:due.value,project:project.value||null,done:false});closeEditor();feedback='';commit()};name.focus()}
$('#add').onclick=editor;$('#sort').onchange=e=>{sort=e.target.value;render()};$('#language').onchange=e=>{if(!state||blocked)return;state.language=e.target.value;closeEditor();feedback='';$('#answer').hidden=true;commit()};function native(action,payload={}){window.webkit?.messageHandlers?.desk.postMessage({action,...payload})}
function renderChat(){const log=$('#chat-log');log.replaceChildren();(state.chat||[]).forEach(m=>{const row=node('div',undefined,'chat-message '+m.role);row.append(node('small',m.role==='user'?t().you:'Codex'),node('p',m.text));log.append(row)});log.scrollTop=log.scrollHeight}
window.chatResult=result=>{if(result.requestID!==chatID)return;chatID=null;chatBusy=false;$('#answer').hidden=false;if(result.ok){state.chat=(state.chat||[]).concat({role:'assistant',text:result.text}).slice(-100);$('#answer').textContent='';save()}else{$('#answer').textContent=t()[result.error]||t().chatError}render()};
$('#mini-toggle').onclick=()=>native('mini');
$('#chat-cancel').onclick=()=>native('cancelChat');
$('#chat-reset').onclick=()=>{if(chatBusy)native('cancelChat');chatID=null;chatBusy=false;state.chat=[];$('#answer').hidden=true;commit()};
$('#question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&e.keyCode!==229){e.preventDefault();$('#chat-form').requestSubmit()}});
$('#chat-form').onsubmit=e=>{e.preventDefault();if(chatBusy||blocked)return;const question=$('#question').value.trim();if(!question)return;if(!window.webkit?.messageHandlers?.desk){$('#answer').hidden=false;$('#answer').textContent=t().nativeOnly;return}const history=(state.chat||[]).slice(-12);state.chat=(state.chat||[]).concat({role:'user',text:question}).slice(-100);chatBusy=true;chatID=crypto.randomUUID();$('#question').value='';$('#answer').hidden=false;$('#answer').textContent=t().thinking;save();render();native('chat',{requestID:chatID,request:{snapshot:M.context(state),history,question}})};
function editProject(p){
 const s=t(),f=$('#editor');f.hidden=false;f.replaceChildren(node('h3',s.editStages));
 const name=node('input');name.value=p.name;name.required=true;name.maxLength=100;f.append(label(s.projectName,name));
 const priority=select([['1',s.critical],['2',s.important],['3',s.normal]],String(p.priority));f.append(label(s.priority,priority),node('p',s.stageHelp));
 const inputs=[],excluded=[];
 M.stages[state.language].forEach((defaultName,i)=>{const row=node('div',undefined,'stage-editor'),input=node('input'),check=node('input');input.value=(p.stageNames||[])[i]||'';input.placeholder=defaultName;input.maxLength=60;check.type='checkbox';check.checked=!M.applicable(p,i);row.append(label(`${i+1}. ${defaultName}`,input),label(s.notApplicable,check));f.append(row);inputs.push(input);excluded.push(check)});
 const actions=node('div',undefined,'buttons'),submit=node('button',s.saveChanges);submit.type='submit';actions.append(button(s.cancel,closeEditor),submit);f.append(actions);
 f.onsubmit=e=>{e.preventDefault();if(!name.value.trim())return;p.name=name.value.trim();p.priority=Number(priority.value);p.stageNames=inputs.map(x=>x.value.trim());p.excluded=excluded.map(x=>x.checked);closeEditor();feedback='';commit()};f.scrollIntoView({block:'start'});
}
window.boot=payload=>{if(payload.error||(payload.state&&!M.valid(payload.state))){blocked=true;$('#error').textContent=payload.error||DeskStrings[payload.language||'en'].invalid;$('#error').hidden=false;$('#workspace').hidden=true;$('#language').disabled=true;return}state=payload.state||{version:2,language:payload.language||'en',projects:[],todos:[]};state.version=2;if(payload.language)state.language=payload.language;if(!payload.state&&!payload.language){$('#workspace').hidden=true;$('#welcome').hidden=false;$('#welcome').append(node('h2','Welcome / 환영합니다'),node('p','Choose your language / 언어를 선택하세요'));['en','ko'].forEach(l=>$('#welcome').append(button(l==='en'?'English':'한국어',()=>{state.language=l;$('#welcome').hidden=true;$('#workspace').hidden=false;commit()})))}else{render();if(payload.language)save()}};
setInterval(()=>{if(state&&!blocked&&lastDate!==M.today()){lastDate=M.today();feedback='';render()}},30000);document.addEventListener('visibilitychange',()=>{if(state&&!blocked){lastDate=M.today();feedback='';render()}});
})();
